add_executable(cpp_parity_tests parity_tests.cpp)
target_link_libraries(cpp_parity_tests PRIVATE horus_cpp_sdk)
add_test(NAME cpp_parity_tests COMMAND cpp_parity_tests)

add_executable(cpp_experiments_tests experiments_tests.cpp)
target_link_libraries(cpp_experiments_tests PRIVATE horus_cpp_sdk)
add_test(NAME cpp_experiments_tests COMMAND cpp_experiments_tests)

add_executable(cpp_color_tests color_tests.cpp)
target_link_libraries(cpp_color_tests PRIVATE horus_cpp_sdk)
add_test(NAME cpp_color_tests COMMAND cpp_color_tests)

