name: Deploy Documentation

on:
  push:
    branches:
      - main
      - docs/complete-documentation
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PYTHON_VERSION: "3.10"

jobs:
  # Build Documentation
  build:
    name: Build Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-docs-${{ hashFiles('docs/**') }}
          restore-keys: |
            ${{ runner.os }}-docs-

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocstrings[python]
          pip install mkdocs-gen-files
          pip install mkdocs-literate-nav
          pip install mkdocs-section-index

      - name: Install HORUS SDK for API docs
        run: |
          pip install -e python/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build documentation
        run: |
          cd docs
          mkdocs build --clean --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site

  # Deploy to GitHub Pages
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/docs/complete-documentation'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
